# Generated by Django 4.1 on 2026-06-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0004_alter_autor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='EixoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
