# Generated by Django 4.2 on 2026-06-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0005_eixotecnologia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
        migrations.AlterModelTable(
            name='eixotecnologia',
            table='eixo',
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('id_fk_autor', models.ForeignKey(db_column='if_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.autor')),
                ('id_fk_eixo', models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.eixotecnologia')),
            ],
            options={
                'db_table': 'artigo',
            },
        ),
    ]
