# Generated by Django 4.2 on 2026-06-25 18:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0006_alter_autor_table_alter_eixotecnologia_table_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=tinymce.models.HTMLField(),
        ),
    ]
